import React from 'react';
import { Sparkles, TrendingUp, AlertTriangle, Building, Briefcase, Info } from 'lucide-react';
import { repo } from '../../services/storage';

export const PredictiveAnalyticsScreen: React.FC = () => {
  return (
    <div className="space-y-6">
      {/* Header with Mandatory AI Disclaimer */}
      <div>
        <div className="flex items-center gap-2">
          <h1 className="text-xl lg:text-2xl font-black text-white tracking-tight">
            Predictive Placement Intelligence & Forecasts
          </h1>
          <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-purple-500/20 text-purple-300 border border-purple-500/30 flex items-center gap-1">
            <Sparkles className="w-3 h-3" />
            AI PREDICTION
          </span>
        </div>
        <p className="text-xs text-slate-400 mt-1">
          Machine learning forecasts modeled on historical campus hiring patterns, student readiness trajectories, and macroeconomic tech demand.
        </p>
      </div>

      {/* Mandatory Notice */}
      <div className="p-3.5 rounded-xl bg-purple-950/30 border border-purple-500/40 text-xs text-purple-200 flex items-start gap-2.5">
        <Info className="w-4 h-4 text-purple-400 shrink-0 mt-0.5" />
        <div>
          <strong className="font-bold">Algorithmic Predictive Model Disclaimer:</strong> All projections displayed below are labeled as <strong>[AI Prediction]</strong> generated by statistical regression and LLM trend models. They are probabilistic estimates designed for strategic TPO intervention planning, not guaranteed contractual outcomes.
        </div>
      </div>

      {/* 5 Core Predictions Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {/* Forecast 1 */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 border border-purple-500/30">
              AI PREDICTION
            </span>
            <span className="text-xs text-slate-400 font-mono">92% Confidence</span>
          </div>
          <h3 className="font-bold text-sm text-white">Final Cohort Placement Rate Forecast</h3>
          <div className="text-3xl font-black text-emerald-400 font-mono">
            88.4% - 91.2%
          </div>
          <p className="text-xs text-slate-400">
            Based on upcoming confirmed Tier-1/Tier-2 drives, expected final batch placement will reach ~90% by March 2027.
          </p>
        </div>

        {/* Forecast 2 */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 border border-purple-500/30">
              AI PREDICTION
            </span>
            <span className="text-xs text-slate-400 font-mono">85% Confidence</span>
          </div>
          <h3 className="font-bold text-sm text-white">Offer Acceptance vs Renege Probability</h3>
          <div className="text-3xl font-black text-indigo-300 font-mono">
            84.5% Acceptance
          </div>
          <p className="text-xs text-slate-400">
            Predicted ~15.5% deferral / renege risk driven by multiple dream offers across CSE/IT candidates.
          </p>
        </div>

        {/* Forecast 3 */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 border border-purple-500/30">
              AI PREDICTION
            </span>
            <span className="text-xs text-slate-400 font-mono">89% Confidence</span>
          </div>
          <h3 className="font-bold text-sm text-white">At-Risk Student Remediation Success</h3>
          <div className="text-3xl font-black text-rose-300 font-mono">
            72% Recovery
          </div>
          <p className="text-xs text-slate-400">
            Forecast indicates 3 out of 4 currently flagged at-risk students will clear mass placement cutoffs with active mentor clinics.
          </p>
        </div>

        {/* Forecast 4 */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 border border-purple-500/30">
              AI PREDICTION
            </span>
            <span className="text-xs text-slate-400 font-mono">94% Confidence</span>
          </div>
          <h3 className="font-bold text-sm text-white">Emerging Recruiter Skill Demand Surge</h3>
          <div className="text-base font-extrabold text-white mt-1">
            +38% AI/LLM & Rust Systems
          </div>
          <p className="text-xs text-slate-400">
            Enterprise recruiters will heavily favor distributed systems, Go, and AI agent engineering over generic fullstack in next hiring cycles.
          </p>
        </div>

        {/* Forecast 5 */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-lg space-y-3 lg:col-span-2">
          <div className="flex items-center justify-between">
            <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 border border-purple-500/30">
              AI PREDICTION
            </span>
            <span className="text-xs text-slate-400 font-mono">Recommended TPO Interventions</span>
          </div>
          <h3 className="font-bold text-sm text-white">Strategic Recruiter Engagement Forecast</h3>
          <div className="space-y-2 text-xs text-slate-300">
            <div className="p-2.5 rounded-xl bg-slate-950/60 border border-slate-800">
              • <strong>Semiconductor Surge:</strong> Texas Instruments & Qualcomm have +40% hiring intent for ECE embedded systems.
            </div>
            <div className="p-2.5 rounded-xl bg-slate-950/60 border border-slate-800">
              • <strong>Mass Recruiter Moderation:</strong> TCS & Cognizant campus hiring projected to decline 12%; prioritize mid-tier product firms.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
